version: "3.4"

volumes:
  astro_node_modules:

services:
  todo-api:
    build: todo-api
    image: todo-api
    restart: "no"
    volumes:
      - ./todo-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    deploy:
      replicas: 2

  database:
    container_name: database-server
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:10.5.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true" # Prevent startup on docker-compose up
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - todo-api
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-api
    ports:
      - 7800:7800
  
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  
  todo-ui:
    build: todo-ui
    image: todo-ui
    restart: "no"
    volumes:
      - ./todo-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - todo-api